version: '3.8'

services:
  # Redis Cache (for caching embeddings and search results)
  redis:
    image: redis:7.2-alpine
    container_name: rag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Enhanced RAG System API
  api:
    build: .
    container_name: rag-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # MongoDB Atlas connection (set in .env file)
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}  # Required for embeddings and AI features
      PORT: 3000
      MAX_FILE_SIZE: 50000000
    volumes:
      - logs_data:/usr/src/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
  logs_data:

networks:
  rag-network:
    driver: bridge
