version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: rag-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-change-me}
      MONGO_INITDB_DATABASE: enhanced-rag-system
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rag-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: rag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - rag-network

  # Enhanced RAG System API
  api:
    build: .
    container_name: rag-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-change-me}@mongodb:27017/enhanced-rag-system?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-change-me}
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY}
      PORT: 3000
      MAX_FILE_SIZE: 50000000
      UPLOAD_PATH: /usr/src/app/uploads
    volumes:
      - uploads_data:/usr/src/app/uploads
      - logs_data:/usr/src/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
  redis_data:
  uploads_data:
  logs_data:

networks:
  rag-network:
    driver: bridge
